###### NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays

In [1]:
pip install numpy
import numpy as np

### space checking

In [2]:
lst = range(1000)

In [3]:
lst

range(0, 1000)

In [4]:
import sys

In [5]:
sys.getsizeof(4)*len(lst)

28000

In [6]:
arr = np.arange(1000)

In [7]:
arr.size*arr.itemsize

4000

### Fastness

In [8]:
lst1 = range(1000000)
lst2 = range(1000000)

In [9]:
import time

In [11]:
start = time.time()
result = [(x+y) for x,y in zip(lst1,lst2)]
print((time.time()-start)*1000)

184.89360809326172


In [12]:
arr1= np.arange(1000000)
arr2= np.arange(1000000)

In [14]:
start = time.time()
result = arr1+arr2
print((time.time()-start)*1000)

18.99242401123047


#### Flexibilty

In [15]:
arr1+arr2

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [16]:
arr2*arr2

array([         0,          1,          4, ..., -733379959, -731379964,
       -729379967])

In [18]:
lst = [1,2,3,3,3,3,3,3,3,3,3,3,3]

In [19]:
lst+lst

[1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

In [20]:
arr2/arr2

C:\Users\SMARTB~1\AppData\Local\Temp/ipykernel_3660/4263725751.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr2/arr2


array([nan,  1.,  1., ...,  1.,  1.,  1.])

### creating a array

In [21]:
a = np.array([1,2,3,4,5])

In [22]:
a

array([1, 2, 3, 4, 5])

In [23]:
a.ndim

1

In [24]:
a = np.array([[2,3,4,5],[3,4,5,6]])

In [25]:
a

array([[2, 3, 4, 5],
       [3, 4, 5, 6]])

In [26]:
a.ndim

2

In [27]:
a = np.array([[2,3,4,5],[3,4,5,6],[3,4,5,5,]])

In [28]:
a

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [3, 4, 5, 5]])

In [29]:
a.ndim

2

#### zeros and one's

In [30]:
var = np.zeros(10)

In [31]:
var

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
var = np.zeros((3,4,5))

In [39]:
var

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [40]:
var.ndim

3

In [41]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# functions

In [43]:
var = np.array([22,33,44])

In [44]:
var

array([22, 33, 44])

In [45]:
type(var)

numpy.ndarray

In [46]:
var.argmax()  # max value in index position

2

In [47]:
var.argmin() # min index values

0

In [48]:
var.data

In [49]:
var.dtype

dtype('int32')

In [50]:
var.dtype.name

'int32'

In [51]:
var.itemsize

4

In [52]:
var

array([22, 33, 44])

In [53]:
var[1]

33

In [54]:
var[0]

22

In [55]:
var[0:2]

array([22, 33])

In [56]:
var[0:3]

array([22, 33, 44])

In [57]:
lst = [3,4,5]

In [58]:
lst

[3, 4, 5]

In [59]:
lst[1] = 444

In [60]:
lst

[3, 444, 5]

In [61]:
var

array([22, 33, 44])

In [62]:
var[0] = 1000

In [63]:
var

array([1000,   33,   44])

In [65]:
arr = np.array([[1,2,3,4],[2,3,4,5]], dtype = complex)

In [66]:
arr

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j]])

In [67]:
# print an array with 10 values by giving max and min
aa = np.linspace(0,2,10)

In [68]:
aa

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [69]:
np.sin(aa)

array([0.        , 0.22039774, 0.42995636, 0.6183698 , 0.77637192,
       0.8961922 , 0.9719379 , 0.99988386, 0.9786557 , 0.90929743])

In [70]:
np.tan(aa)

array([ 0.        ,  0.22595393,  0.47622143,  0.78684289,  1.23179859,
        2.01997033,  4.13172899, 65.60839711, -4.76215913, -2.18503986])

In [71]:
np.tanh(aa)

array([0.        , 0.21863508, 0.41732165, 0.58278295, 0.7108445 ,
       0.8044548 , 0.87006166, 0.9146975 , 0.94445565, 0.96402758])

In [72]:
from numpy import pi

In [73]:
pi*aa

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [75]:
0.21863508*pi

0.6868623611450168

#### reshape and resize

In [76]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [78]:
a.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [79]:
a.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [80]:
rnge = np.random.default_rng(2)

In [81]:
a = rnge.random((3,4))

In [82]:
a

array([[0.26161213, 0.29849114, 0.81422574, 0.09191594],
       [0.60010053, 0.72856053, 0.18790107, 0.05514663],
       [0.27496937, 0.65743301, 0.56226566, 0.15006226]])

In [83]:
a.sum()

4.682684022737332

In [84]:
a.sum(axis = 0)

array([1.13668203, 1.68448469, 1.56439248, 0.29712483])

In [86]:
a.sum(axis = 1)

array([1.46624496, 1.57170875, 1.64473031])

In [87]:
a.cumsum()

array([0.26161213, 0.56010328, 1.37432902, 1.46624496, 2.06634549,
       2.79490601, 2.98280709, 3.03795371, 3.31292308, 3.9703561 ,
       4.53262176, 4.68268402])

In [88]:
a.cumprod()

array([2.61612134e-01, 7.80889051e-02, 6.35819966e-02, 5.84419912e-03,
       3.50710696e-03, 2.55513970e-03, 4.80113492e-04, 2.64766398e-05,
       7.28026491e-06, 4.78628651e-06, 2.69116456e-06, 4.03842244e-07])

In [89]:
a

array([[0.26161213, 0.29849114, 0.81422574, 0.09191594],
       [0.60010053, 0.72856053, 0.18790107, 0.05514663],
       [0.27496937, 0.65743301, 0.56226566, 0.15006226]])

In [90]:
a.max()

0.8142257405942803

In [91]:
a.min()

0.05514662733306819

In [92]:
q = 567890

In [93]:
np.sqrt(q)

753.5847663003811

In [94]:
x = [1,2,3,5,6]

In [96]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.23606798, 2.44948974])

In [97]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.60943791, 1.79175947])

In [98]:
np.exp(x)

array([  2.71828183,   7.3890561 ,  20.08553692, 148.4131591 ,
       403.42879349])

In [99]:
a

array([[0.26161213, 0.29849114, 0.81422574, 0.09191594],
       [0.60010053, 0.72856053, 0.18790107, 0.05514663],
       [0.27496937, 0.65743301, 0.56226566, 0.15006226]])

In [101]:
a.shape

(3, 4)

### transpose

In [102]:
aa = a.T

In [103]:
aa.shape

(4, 3)

## reverse

In [104]:
a

array([[0.26161213, 0.29849114, 0.81422574, 0.09191594],
       [0.60010053, 0.72856053, 0.18790107, 0.05514663],
       [0.27496937, 0.65743301, 0.56226566, 0.15006226]])

In [118]:
aaa =  np.linspace(1,4,10)

In [119]:
aaa

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [110]:
aaa = np.array([[3,3,3],[4,4,4]])

In [115]:
ax = aaa.sort(axis = 0)

In [116]:
ax

In [120]:
aaa

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [123]:
aaa[-1]

4.0

In [121]:
aaa[::-1]

array([4.        , 3.66666667, 3.33333333, 3.        , 2.66666667,
       2.33333333, 2.        , 1.66666667, 1.33333333, 1.        ])

In [122]:
np.floor(4.4)

4.0

In [124]:
np.ceil(5.5)

6.0

In [125]:
np.abs(66.567890)

66.56789